---
page-layout: full
title-block-banner: false
css: custom.css
---
I would like to share my own two cents about futures research and hope that they will encourage further research on futures markets.

# How energy futures markets respond to EIA Weekly Petroleum Status Report?
Futures markets are typically supposed to respond to new information in a timely manner. The U.S. Energy Information Administration (EIA) releases the Weekly Petroleum Status Report every Wednesday at 10:30 a.m. ET...

[Read more →](announcement.qmd)

<center><hr style="width:80%"></center>

# How to rollover futures contracts?
Rolling from an expiring contract to the next one is a common practice in futures trading. Even though it is as simple as closing the front-month leg and opening the back-month leg, there is not so much guidance on how to trade during this period. I find exchange-traded calendar spread contracts are pretty useful for this purpose...

[Read more →](calendar_spreads.qmd)

<center><hr style="width:80%"></center>

# Price discovery
Price discovery is one of the well-known financial terms...

[Read more →](price_discovery.qmd)

<center><hr style="width:80%"></center>

# Continuous Futures Data Construction
Every futures contract has its expiration date, and no data are available afterwards. Thus, we need to construct a "continuous" futures by rolling from an expiring contract to the next one...

[Read more →](rollover.qmd)

<center><hr style="width:80%"></center>

# Price limit days in agricultural futures markets
Price limit is one of the ways that exchanges would use to monitor trading activities, especially extreme price movements. In the agricultural futures markets, CME has implemented different price limit schedules...

[Read more →](price_limits.qmd)