---
page-layout: full
back-to-top-navigation: true
title-block-banner: false
css: custom.css
---
[&larr Go back](futures.qmd){.preview-link}

# Price limit days in agricultural futures markets
* Price limit is one of the ways that exchanges would use to monitor trading activities, especially extreme price movements. In the agricultural futures markets, CME has implemented different price limit schedules.
* A common characteristic is that price limits would "lock" markets when limit prices are reached. It does not mean markets are halted and no trades can occur, like circuit breakers. In fact, trades can still be executed unless only for one side. Specifically, selling during limit-up days and buying during limit-down days.
* CME revises the limit prices routinely according to market conditions and the limit price range can be expandable after the day when price limits are triggered. In 2014 (2015), CME implemented expandable price limits to 4.5 cents/lb. in live cattle (lean hog) futures markets once standard limit criterion is reached.
* (Examples) Price limit events in live cattle outright futures markets during 2015 to 2019 (1st--4th nearby).

| Date       | Contract | High Limit | Low Limit | Day       |
|------------|----------|------------|-----------|-----------|
| 2015-01-27 | LEG5     | 152.83     | 146.83   | limit_up  |
| 2015-01-27 | LEJ5     | 151.00     | 145.00   | limit_up  |
| 2015-02-06 | LEJ5     | 151.03     | 145.03   | limit_up  |
| 2015-02-06 | LEM5     | 144.25     | 138.25   | limit_up  |
| 2015-02-13 | LEJ5     | 154.13     | 148.13   | limit_up  |
| 2017-04-26 | LEQ7     | 115.05     | 109.05   | limit_up  |
| 2017-04-27 | LEG8     | 117.78     | 111.78   | limit_up  |
| 2017-04-27 | LEJ8     | 116.65     | 110.65   | limit_up  |
| 2017-04-27 | LEM7     | 121.53     | 115.53   | limit_up  |
| 2017-05-02 | LEM7     | 127.13     | 121.13   | limit_up  |

Click here to get the full price limit events for [live cattle](https://www.dropbox.com/scl/fi/k5tkz5sy3vuo8lqt98lia/live_cattle_limit_days.csv?rlkey=jwkk1q5nfc8150fr8hh6mgxsy&dl=0) and [lean hog](https://www.dropbox.com/scl/fi/d04ig9zbv7ezg4b4hz2k4/lean_hog_limit_days.csv?rlkey=505gc8f7ev8vwd8bmrmeeggro&dl=0).

Thoughts or questions?  
[Thoughts and questions](mailto:ruchuan2@illinois.edu?subject=Comment%20on%20Price%20Limits){.btn .btn-outline-primary}