---
page-layout: full
title-block-banner: false
css: custom.css
---

# Peer-reviewed Publications
## Commodity trading
<details class="abstract-fold" open>
<summary>
**Richie R. Ma** and [Teresa Serra](https://ace.illinois.edu/directory/tserra). [**Is liquidity provision informative? Evidence from agricultural futures markets**](https://onlinelibrary.wiley.com/doi/full/10.1111/ajae.12479). ***American Journal of Agricultural Economics***, January 2025
</summary>
<p>
 **Abstract**:
 Electronic commodity trading witnesses a massive volume of order messages every trading day, but little is known about their informativeness. We examine limit order dynamics and their role in price discovery in the Chicago Mercantile Exchange (CME) corn, soybean, and wheat futures markets from January 2019 to June 2020, using order-level data. Between 75% and 79% of the large number of limit orders submitted are then deleted, which contrasts with the much smaller proportion getting executed or revised. Aggressive trades and limit orders substantially contribute to price discovery, whereas nonaggressive trades and limit orders, representing most market events, play a minor role. Following public information releases, there is a shift in trading strategies, with trades contributing more to price discovery and aggressive limit orders contributing less, compared to non-release days. Our findings suggest that most limit orders in agricultural futures markets continue to play the traditional role of uninformed liquidity provision.
</p>
</details>

* [SSRN version](https://www.dropbox.com/scl/fi/2a96f0lf5lowb59d6j75n/Is-liquidity-provision-informative-Evidence-from-agricultural-futures-markets_SSRN.pdf?rlkey=fo8h0epmddicp75h4pm3awk0t&dl=0); [AFA version](https://afajof.org/management/viewp.php?n=63476); [Internet Appendix](https://www.dropbox.com/scl/fi/hxwnuwjh1e1wfk6lgdv7h/AJAE_online_appendix.pdf?rlkey=o1fmsl524u9vpisbv87gwxkch&e=1&dl=0); [Replication Codes](https://www.dropbox.com/scl/fi/2tty65wu3lzevcvoped09/Replication_Codes.zip?rlkey=ajs0urgpp5utflh9ewgvwiw27&dl=0); [CME Data Cleaning Notes](https://www.dropbox.com/scl/fi/c38mrquy6a3vv03vbqf0v/Data-cleaning.pdf?rlkey=faameal5226tjk1m2gislsr6o&dl=0); [AFA Poster](https://www.dropbox.com/scl/fi/ie29qk29udjt0z632s5y8/AFA2024_poster.pdf?rlkey=gd4grb3obucbk67cddqy40i76&dl=0); [Slides](https://www.dropbox.com/scl/fi/fwxjdti81lot61jtgwkyr/AJAE-slides.pdf?rlkey=op6t73upmgrb3duyye2esq8pu&dl=0)
* Previously circulated under the title ["Limit orders and price discovery: Evidence from agricultural futures markets"](https://afajof.org/management/viewp.php?n=63476)
* Subsuming my [Master Thesis](https://www.ideals.illinois.edu/items/126670) at the UIUC by using a new dataset and adding analysis related to USDA public announcements.
* **Presentations**: 2024 AFA Ph.D. Poster Session; 2023 NCCC-134 Conference; UIUC ACE Commercial Ag
* **Award**: 2024 Peer-Reviewed Research Achievement, ACE Dept, UIUC</span>

## Futures markets and price analysis
<details class="abstract-fold">
<summary>
**Richie R. Ma**, [Tao Xiong](https://www.xiongtao.cc/home), and Yukun Bao. [**The Russia-Saudi Arabia oil price war during the COVID-19 pandemic**](https://www.sciencedirect.com/science/article/pii/S0140988321003984?via%3Dihub). ***Energy Economics***, October 2021
</summary>
<p>
 **Abstract**:
 The COVID-19 pandemic damaged crude oil markets and amplified the consequences of uncertainty stemming from the Russia-Saudi Arabia oil price war in March-April of 2020. We investigate the impacts of the oil price war on global crude oil markets. By doing so, we use the daily futures and spot prices in three major crude oil markets – West Texas Intermediate, European Brent, and Oman – to perform a systematic analysis of the impacts of the oil price war on them. The event study method, a well-established analytical tool to measure the impacts of a given event on markets, is used in this study. The results indicate that information leakage plays an important role in the impacts of the price war. The outbreak of and truce following the price war have asymmetrical impacts on the markets; negative impacts generated by information leakage during the outbreak are generally more durable than the positive ones it generated during the truce. Furthermore, the magnitude of the impacts on futures markets is negatively correlated with the time-to-maturity of futures. Finally, negative crude oil prices affect West Texas Intermediate crude oil markets the most. Our findings generally show that market participants could perceive and assimilate market changes and adjust their expectations, which restrained the impacts that should have occurred within the oil price war.
</p>
</details>

<center><hr style="width:100%"></center>

<details class="abstract-fold">
<summary>
**Richie R. Ma** and [Tao Xiong](https://www.xiongtao.cc/home). [**Price explosiveness in nonferrous metal futures markets**](https://www.sciencedirect.com/science/article/pii/S0264999320311962?via%3Dihub). ***Economic Modelling***, January 2021
</summary>
<p>
 **Abstract**:
 Whether high price volatility could reflect market fundamentals is still open to debate, although the literature has established the presence of price explosiveness in many financial markets. Using the futures prices of six dominant nonferrous metals in 2014–2018, we investigate the characteristics and determinants of price explosiveness in nonferrous metal futures markets. We find that during the past 15 years, the markets have displayed price explosiveness and they have limited ability to adjust to price changes. High interest rates would trigger price explosiveness through high investment cost, while a high exchange rate would decrease it by increasing nonferrous metal availability. An exuberant stock market would reduce price explosiveness by migrating risk from nonferrous metal markets. A booming economic environment causes price explosiveness through increased demand for nonferrous metals. Our findings refute the notion that market fundamentals can exclusively drive futures prices, even in the context of high price volatility.
</p>
</details>

# Work in progress
**Grain merchandising and crop insurance: Evidence from the U.S. corn belt**

**Local cash–futures basis and climate-related natural disasters: Corporate spillover effects**

**The impact of freight chokepoints on U.S. soybean exports: Evidence from the Panama Canal** with Teresa Serra. 

**Trademarks from local specialties: The documentary effect of *A Bite of China*** with Zhankun Chen (CUHK) and [Yiyi Zhao](https://yiyizhao.weebly.com/) (CUHK).

**Finer prices, better liquidity? Tick size, market quality, and price discovery in Chinese soybean oil futures markets** with Xiaoyi Fang (U Arkansas)

**Futures price limits and options trading: Evidence from livestock markets** with Xiaoyi Fang (U Arkansas)

# Working Papers
## Commodity trading
<details class="abstract-fold" open>
<summary>
**Richie R. Ma**, [Brian G. Peterson](https://giesbusiness.illinois.edu/profile/brian-peterson), and [Teresa Serra](https://ace.illinois.edu/directory/tserra). **Who benefits from a faster exchange? Evidence from agricultural futures electronic trading [Job market paper]** *Draft coming soon*.
</summary>
<p>
 **Abstract**:
 As trading has transitioned to electronic platforms, both traders and exchanges have invested in technologies that reduce trading latency. Yet little is known about how exchange processing latency affects market quality or whether its effects differ across market participants. Using message data from the Chicago Mercantile Exchange (CME), we examine these effects and their distribution between liquidity providers and liquidity takers. To address endogeneity, we exploit cross-commodity processing congestion arising from the shared order-processing system as an instrument for exchange latency. We find that lower exchange latency primarily benefits liquidity providers by increasing market-making revenues while reducing adverse selection costs, but can increase the immediate trading costs borne by liquidity takers. Our findings also reveal a congestion-based externality across commodity markets and highlight the importance of processing capacity in exchange design.
</p>
</details>

<center><hr style="width:100%"></center>

<details class="abstract-fold" open>
<summary>
**Richie R. Ma** and [Teresa Serra](https://ace.illinois.edu/directory/tserra). **When options lead and futures inform: Price discovery in agricultural derivatives markets**. *Revise and Resubmit at European Review of Agricultural Economics*
</summary>
<p>
 **Abstract**:
 Electronic trading allows prices to impound information through both trades and aggressive quotes at the top of the limit order book. Agricultural options markets exhibit frequent aggressive quoting despite thin trading activity, yet little is known about how they contribute to price discovery relative to their underlying futures. Using Chicago Mercantile Exchange (CME) intraday data, this paper examines price discovery between agricultural futures and options, documenting a contrast between timeliness and informativeness. Options incorporate new information more quickly than the underlying futures, yet futures remain the primary source of price informativeness. We find that a 1% increase in relative aggressive quoting is associated with a 0.25% increase in options’ timeliness leadership and a 0.15% decline in their relative informativeness. By contrast, options’ relative trading volume is negatively associated with their timeliness advantage and is unrelated to informativeness.
</p>
</details>


* [AAEA version](https://ageconsearch.umn.edu/record/404352?ln=en&v=pdf); [Slides](https://www.dropbox.com/scl/fi/cdib5p3dbgaqw3bk12m9g/Options-slides.pdf?rlkey=bw3jf9b11i0pvfw8qsj9kqd3n&dl=0)
* Subsuming the 1st chapter of my PhD dissertation at the UIUC.
* **Presentations**: Inter–Finance PhD; UIUC ACE FACS; 2024 Summer School on Market Microstructure; 2025 AFA Annual Meeting Ph.D. Poster Session; 2025 SWFA Annual Meeting; 2025 MFA Annual Meeting; 2025 NCCC–134 Conference; 2026 AAEA Annual Meeting

<center><hr style="width:100%"></center>

<details class="abstract-fold" open>
<summary>
**Richie R. Ma**, [Teresa Serra](https://ace.illinois.edu/directory/tserra), [Brian G. Peterson](https://giesbusiness.illinois.edu/profile/brian-peterson), and [Scott H. Irwin](https://scotthirwin.com/). **One contract, two deals: Do exchange-traded calendar spreads matter?** *Under Review*
</summary>
<p>
 **Abstract**:
 Electronic trading allows traders to execute calendar spreads simultaneously rather than pairing two outright contracts. Through implied functionality, calendar spreads and outrights are tightly connected, reshaping liquidity provision in outright markets. We examine how the trading architecture of calendar spreads affects the trading outcomes for different groups of agricultural futures market participants. Using Chicago Mercantile Exchange (CME) intraday data, we focus on spread traders who rely on calendar spreads to meet their trading needs, and outright market makers. Counterfactual analyses show that calendar spreads improve execution quality and generate more informative signals about the futures term structure. Implied functionality increases adverse-selection risk borne by market makers, while leaving their gross revenues largely unchanged. Our findings highlight the trade-offs inherent in the current calendar-spread trading design.  
</p>
</details>

* [NCCC-134 version](https://farmdoc.illinois.edu/publications/one-contract-two-deals-electronic-trading-design-of-exchange-traded-calendar-spreads)
* Subsuming the 2nd chapter of my PhD dissertation at the UIUC.
* **Presentations**: UIUC ACE FACS; 2026 NCCC–134 Conference

<center><hr style="width:100%"></center>

<details class="abstract-fold">
<summary>
**Richie R. Ma** and [Teresa Serra](https://ace.illinois.edu/directory/tserra). **One-tick futures: Does tick size reduction better markets?**
</summary>
<p>
 **Abstract**:
 This paper examines tick size reduction in the U.S. 2-year Treasury Note futures marketaround January 14, 2019. We employ a difference-in-differences regression with 5-, 10-,and ultra 10-year Treasury futures markets as control groups, and we generally findsignificantly improved market quality. Trading costs reduce for liquidity takers andthe smaller tick size has limited ability to relax its binding constraint. Our mechanismanalyses indicate that traders significantly withdraw less liquidity after undercutting inresponse to non-execution risks and when they react to snipping risks at the oppositeside of undercutting orders. Moreover, we find traders do not shift to market ordersto acquire immediacy. Conversely, significantly fewer trades after undercutting. Thesmaller tick size significantly changes the quoting behavior, where depths are dispersedthrough the new pricing grid, suggesting that traders can post price-improving quotesand limit orders are layered in a more granular pricing grid, with limit order sizesignificantly becoming smaller. Last, trading volume does not significantly change,while more trades occur with smaller trade size. Pricing efficiency does not significantlychange neither does price discovery. Our findings suggest that reducing the tick size intick-constrained liquid futures market could be promising. 
</p>
</details>

* **Presentations**: UIUC ACE FACS; 2024 NCCC-134 Conference