---
page-layout: full
back-to-top-navigation: true
title-block-banner: false
css: custom.css
---
[← Go back](futures.qmd){.preview-link}

# Futures Rollover
* Every futures contract has its expiration date, and no data are available afterwards. Thus, we need to construct a "continuous" futures by rolling from an expiring contract to the next one. 
* Typically, three ways can be considered
  * Rolling directly at the expiration day.
  * Rolling at the last day of the month prior to the expiring contract month.
  * Rolling based on trading volume or open interest. 

The first method typically works well in stock index futures since no obvious seasonality exists in this type of futures. For daily analyses, you might also see researchers apply the first method in crude oil markets. 

The second method is one of the most common ways to roll futures contracts for agricultural futures.

* Typically, the rolling day is close to futures First Notice Day when futures contracts start their delivery process. 
* Literature holds a conventional wisdom that futures research should not include the delivery period. 
  * Paul (1986, p. 321) states that “…it is prudent practice in most studies of futures price behavior to exclude delivery month prices from the analyses…”^[ Paul, A.B. 1986. Liquidation Bias in Futures Price Spreads. American Journal of Agricultural Economics 68 (2):313–321.] 
  * Recent work by Irwin, Sanders, Smith, and Yan about "liquidation bias" also reinforces it.^[Irwin, Scott and Sanders, Dwight R. and Smith, Aaron and Yan, Lei, Was Allen Paul Right? Liquidation Bias in Commodity Futures Markets. Available at SSRN: https://ssrn.com/abstract=6071584]

The third method might be the most-widely-used approach, especially in microstructure analyses because this method considers futures trading the most.

* Typically, the most-traded contracts show the best market liquidity, such as bid-ask spread and market depth. 
  * Generally, the constructed continuous futures series rarely see jumps in market liquidity indicators. 
* One drawback of this method is called the "rolling back" issue. Once we roll to the next contract month, we should not go back though sometimes the previous contract month might have higher trading volume for few days. 
  * In agricultural futures markets, this issue typically occurs when we roll July contract in corn. During this window, the most-traded contract may periodically switch back and forth between July and September. 
* Thus, to control this, researchers need to set another criterion: the trading volume of new contract we roll to should be higher than taht of the expiring one for at least a few consecutive trading days (typically 2 or 3 days). Otherwise, no rolling happens. 
* Using open interest is likely to generate a pretty similar rolling schedule as open interest is highly and positively correlated with trading volume.

In my research, I find that the roll date generated by the third method is typically earlier than that generated by the second method, suggesting that market participants shift their trading attention to the next contract before the First Notice Day.

Thoughts or questions?  
[Thoughts and questions](mailto:ruchuan2@illinois.edu?subject=Comment%20on%Futures%20Rollover){.btn .btn-outline-primary}